Sprint 6 development > master PR
R2D2-2018/ROBOT_CLAW pull request #12
Opened 2018-06-26 11:57 UTC by Michelbaartman

https://trello.com/b/WIO3vVmc/robot-claw
Vertical slice 5
https://trello.com/c/UhcSvabb/50-vs5-robot-claw-slice

2018-06-27 11:05 UTC, wvanbreukelen requested changes
Some small changes to be made.

2018-06-27 11:05 UTC, wvanbreukelen commented on src/main.cpp
> +    /// Check if the uArm is connected.
Use ///< style comments

2018-06-27 11:05 UTC, wvanbreukelen commented on src/claw.cpp
> +ClawFeedback Claw::decodeGcodeResponse(char *response, size_t responseSize) {
Not using the ```responseSize``` parameter.

2018-06-27 11:05 UTC, wvanbreukelen commented on src/claw.cpp
> +            /// If we have the Gcode response `$n ok V1` we only want to return the stuff behind the V mark (in this
Use ///< style comments

2018-06-27 11:05 UTC, wvanbreukelen commented on src/claw.cpp
> +        /// Response format: $n ok V1\n
Use ///< style comments

2018-06-27 11:05 UTC, wvanbreukelen commented on src/claw.cpp
> +                /// We have found a endline. If the response char counter is larger then zero
Use ///> style comments

2018-06-27 13:43 UTC, JasperSmienk commented
@wvanbreukelen We processed your feedback.

2018-06-28 10:16 UTC, wvanbreukelen approved these changes

2018-06-28 10:16 UTC, merged