Development to master
R2D2-2018/ROBOT_CLAW pull request #6
Opened 2018-06-04 12:30 UTC by SamZand

PR from dev to master

Main changes:
- Written ```claw.isConnected()``` method to check if the uArm Swift Pro is connected.
- User are able to receive the current state of the robotic claw using the ```claw.getState()``` method.
- Removed inessential methods in Claw class that are not going to be used.
- Improved firmware version and claw state parsing.
- Improved documentation.
https://trello.com/c/SURK0XsN/27-vs4-robot-claw-slice

2018-06-10 08:43 UTC, elsavira submitted a review, later dismissed
Fix --recursive in this request.

2018-06-10 08:43 UTC, Qperquin commented on src/claw.cpp
> +    /// By giving a null pointer as a method parameter, we save unnecessarily memory space.
unnecessary*

2018-06-10 08:43 UTC, Qperquin commented on src/claw.cpp
> +    /// Add a \0 character to the response, if the is a response.
there*

2018-06-10 08:47 UTC, elsavira requested changes
Fix Travis test by adding --recursive tag for fetch-build-environment.sh

2018-06-19 11:52 UTC, Michelbaartman commented
@Qperquin Changes made by @j00st.

2018-06-19 17:43 UTC, elsavira approved these changes

2018-06-19 17:44 UTC, merged